import type { Mesh, PlaneGeometry, ShaderMaterial, Vector2 } from "three";

export type BendMode = "vertical" | "horizontal" | "both";

export type CarouselConfig = {
  radius: number;
  pitch: number;
  angleStep: number;
  curve: number;
  cardWidth: number;
  cardHeight: number;
  shingle: number;
  backfaceFade: number;
  fogNear: number;
  fogFar: number;
  fogStrength: number;
  depthBlur: number;
  lift: number;
  cameraZ: number;
  fov: number;
  wheelStrength: number;
  dragStrength: number;
  ease: number;
  autoSpin: number;
  snap: boolean;
  snapSpeed: number;
  snapDelay: number;
  snapStiffness: number;
  snapDamping: number;
  entry: boolean;
  entryDuration: number;
  entryStagger: number;
  entryCurve: number;
  entrySoftness: number;
  entryScale: number;
  entryRound: number;
  entrySpin: number;
  entrySpinDuration: number;
  entryEaseIn: number;
  entryEaseOut: number;
  entryDither: number;
  entryDitherLevels: number;
  entryDitherDissolve: number;
  entryDitherInk: string;
  entryDitherAccent: string;
  entryDitherPaper: string;
  entryDitherGamma: number;
  entryDitherMono: number;
  hoverInEase: number;
  hoverOutEase: number;
  hoverCurve: number;
  dimFade: number;
  hoverClean: number;
  hoverIntent: boolean;
  hoverSettleSpeed: number;
  focusFalloff: number;
  hoverBlur: number;
  hoverBlurCurve: number;
  hoverDither: number;
  hoverDitherCurve: number;
  hoverDitherLevels: number;
  hoverDitherScale: number;
  hoverDitherCutoff: number;
  hoverDitherInk: string;
  hoverDitherAccent: string;
  hoverDitherPaper: string;
  hoverDitherGamma: number;
  hoverDitherMono: number;
  clickToFocus: boolean;
  clickSlop: number;
  focusDuration: number;
  focusEaseIn: number;
  focusEaseOut: number;
  cardBufferScale: number;
  bend: number;
  bendMode: BendMode;
  bendEase: number;
  bendMaxVelocity: number;
  focusSize: number;
  edgePower: number;
  blurStrength: number;
  streakAngle: number;
  streakSpread: number;
  streakAnisotropy: number;
  coupling: number;
  stageStreakEnd: number;
  stageDitherBegin: number;
  stageHandoff: number;
  dither: boolean;
  ditherAmount: number;
  ditherStart: number;
  ditherPower: number;
  ditherDepth: number;
  ditherScale: number;
  maxLevels: number;
  minLevels: number;
  fadeStrength: number;
  ditherInk: string;
  ditherAccent: string;
  ditherPaper: string;
  ditherGamma: number;
  ditherMono: number;
  ditherDissolve: number;
  trail: boolean;
  trailRadius: number;
  trailSpeedInfluence: number;
  trailSpeedRange: number;
  trailDecay: number;
  trailDissipate: number;
  trailSmoothing: number;
  trailIdleDelay: number;
  trailIdleDecay: number;
  trailIdleDrift: boolean;
  trailAmount: number;
  trailCutoff: number;
  trailWarp: number;
  trailAberration: number;
  trailContrast: number;
  trailScale: number;
  trailLevels: number;
  trailDissolve: number;
  trailInk: string;
  trailAccent: string;
  trailPaper: string;
  trailGamma: number;
  trailMono: number;
  trailRim: number;
  trailRimColor: string;
  trailRimThickness: number;
  trailRimSoftness: number;
  background: string;
};

export type CardUserData = {
  hoverRaw: { hover: number; dim: number };
  entry: number;
  entryOrder: number;
  visibleMaterial?: ShaderMaterial;
  bufferMaterial?: ShaderMaterial;
};

export type CardMesh = Mesh<PlaneGeometry, ShaderMaterial> & {
  userData: CardUserData;
};

export type ScrollState = {
  target: number;
  current: number;
  velocity: number;
  bendVelocity: number;
  snapVelocity: number;
  snapping: boolean;
};

export type CreateCarouselOptions = {
  images: readonly string[];
  config: CarouselConfig;
  pointer: boolean;
  trail: boolean;
  getPageSlot: () => number;
  isPaused: () => boolean;
  onActiveChange?: (index: number) => void;
  onCardClick?: (index: number) => void;
};

export type CoverRatio = Vector2;
